### ISSUE TITLE
Several RDS DSC resources from Azure RDS ARM template not included

### ISSUE THREAD

**Issue by scottpas** [PowerShell/xRemoteDesktopSessionHost#31]
Can these additional resources be merged into the module published in PS Gallery? Or is there a reason why they aren't?

https://github.com/Azure/RDS-Templates/tree/master/DSC/Configuration/xRemoteDesktopSessionHost/DSCResources

**Comment by scottpas** [comment]
Whoops, I didn't realize this is a duplicate of issue #6

**Comment by johlju** [comment]
@scottpas Referenced this issue in issue #8 instead. Closing this as duplicate.
