### ISSUE TITLE
xRDSessionDeployment Results in "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by mjcarrabine** [PowerShell/xRemoteDesktopSessionHost#39]
When I try to deploy the `xRDSessionDeployment` resource on a new Windows Server 2016 machine, I am getting this error message:

> "Message":  "The PowerShell DSC resource \u0027[xRDSessionDeployment]Deployment\u0027 with SourceInfo \u0027::184::3::xRDSessionDeployment\u0027 threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.",
>                       "Data":  { },
>                       "InnerException":  {
>                                              "ErrorRecord":  "You cannot call a method on a null-valued expression.",
> 

In **#24  Fix Issue where DSC configuration gets into a reboot loop**, line 72
```PowerShell
(Get-TargetResource @PSBoundParameters).SessionHost -ieq $SessionHost
```
was changed to 
```PowerShell
# We need to perform the following check case insensitive because in some
# cases the SessionHost of Get-TargetResource is uppercase while the
# $sessionHost parameter is lowercase causing a reboot loop to happen.
(Get-TargetResource @PSBoundParameters).SessionHost.ToLower() -ieq $SessionHost.ToLower()
```

If New-RDSessionDeployment has not yet been run, then `(Get-TargetResource @PSBoundParameters).SessionHost` is null and calling `.ToLower()` results in the exception. 

On a related note, `-ieq` is already case-insensitive so is `.ToLower()` needed here? Unit tests would help verify whether #24 is resolving the issue mentioned in the code comments.

**Comment by johlju** [comment]
Both `-ieq` and `-eq` are case insensitive, so doesn't understand the need to make the strings lower-case. Looking at the [initial reported issues](https://gallery.technet.microsoft.com/scriptcenter/xRemoteDesktopSessionHost-4a11f27d/view/Discussions) it feels to me that this had to be something else. 🤔 

Agree that there should be a unit test to test this!

Labeling this as a bug and help wanted so anyone in the community can run with this.

**Comment by danielboth** [comment]
Hi @mjcarrabine, can you share the configuration you are using that triggers this error please? I feel that xRDSessionDeployment needs a proper redesign anyway (as is discussed in #21 as well). So if I get some spare time I'll be on that. In the mean time, I'm running this in production without any errors, so I'm wondering what is triggering the issues on your side.

**Comment by danielboth** [comment]
Thanks for the detailed reply @mjcarrabine ! I think the .toLower() part was done in error in a previous PR, so I have reverted that in PR #42. Also, I changed the logic to actually compare the CollectionBroker name instead of the SessionHost, since SessionHosts can be added & removed from a deployment. I think this will fix your issue as well.
