### ISSUE TITLE
Missing xRDServer resource?

### ISSUE THREAD

**Issue by figueroadavid** [PowerShell/xRemoteDesktopSessionHost#40]
Is this resource actually missing from the module?  It is in the readme, but when I check it is not there?
```powershell
PS C:\> Get-DscResource -Module xremotedesktopsessionhost

ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      xRDRemoteApp              xRemoteDesktopSessionHost      1.6.0.0    {Alias, CollectionName, DisplayN...
PowerShell      xRDSessionCollection      xRemoteDesktopSessionHost      1.6.0.0    {CollectionName, SessionHost, Co...
PowerShell      xRDSessionCollectionCo... xRemoteDesktopSessionHost      1.6.0.0    {CollectionName, ActiveSessionLi...
PowerShell      xRDSessionDeployment      xRemoteDesktopSessionHost      1.6.0.0    {ConnectionBroker, SessionHost, ...
```

I'm looking to use this to configure my hosts that won't be part of an RDS Deployment.. 

Thanks, 

David F.

**Comment by figueroadavid** [comment]
For some reason, the edit on my post is being eaten/rejected, etc..
I am specifically looking for the xRDServer resource.. 

David F.

**Comment by johlju** [comment]
It do exist in the code https://github.com/PowerShell/xRemoteDesktopSessionHost/tree/dev/DSCResources/MSFT_xRDServer, not sure why you are not seeing it though.

**Comment by danielboth** [comment]
Hi @figueroadavid, the xRDServer resource was just added and will be released in the next version of xRemoteDesktopSessionHost. If you want to use it right now, just clone the repository or download the zip of the dev branch, this will include xRDServer.

**Comment by johlju** [comment]
I was just about to say what @danielboth said ☺️ thanks Daniel!

**Comment by figueroadavid** [comment]
Great!  thank you so much.. I was really scratching my head on this one.

I am trying to build out DSC for RDS hosts that could be used in Citrix or
VMware, and in those circumstances, the collections are just not
necessary.   One thing I hope you guys will add, is that when using DSC to
enable RDS, the option to turn off the requirements for NLA as part of that
step.

Thanks again,

David F.

**Comment by johlju** [comment]
@figueroadavid please submit a new issue, for the suggested enhancement.

Leaving this open until we release if others have the same question.

**Comment by johlju** [comment]
This is released now, so closing this issue.
