### ISSUE TITLE
xRDServer: parameter typo GateewayExternalFqdn

### ISSUE THREAD

**Issue by peppekerstens** [PowerShell/xRemoteDesktopSessionHost#50]
https://github.com/PowerShell/xRemoteDesktopSessionHost/blob/df7c4d96c27adae1b72eaa13e07529c40addb1d9/DSCResources/MSFT_xRDServer/MSFT_xRDServer.psm1#L173

**Comment by Mobe1969** [comment]
Any update on this? A new release?
