### ISSUE TITLE
xRDSessionDeployment: Not checking/limiting on connectionbroker validity

### ISSUE THREAD

**Issue by peppekerstens** [PowerShell/xRemoteDesktopSessionHost#53]
#### Details of the scenario you tried and the problem that is occurring
Scenario: new deployment 

#### Verbose logs showing the problem
[enhancement]
right now, this Get-TargetResource assumes(?) that it is being targeted by the ConnectionBroker parameter. but does not actually check if provided parameter value and targeted hostname are the same.

#### Suggested solution to the issue
A simple check in the Get-TargetResource on provided ConnectionBroker value and the targetted hostname.

**Comment by johlju** [comment]
Labeled this as an enhancement and help wanted so that anyone in the community can pick this up.
