### ISSUE TITLE
Is xRDLicenseConfiguration Available in Any Releases?

### ISSUE THREAD

**Issue by mjcarrabine** [PowerShell/xRemoteDesktopSessionHost#59]
I'm not sure if I am asking this question correctly, but I hope someone will understand.

If I run this command to install version 1.6.0.0 of xRemoteDesktopSessionHost
``` powershell
install-module -name xRemoteDesktopSessionHost
```

I am able to add these resources in my configuration file:
  - `xRDRemoteApp`
  - `xRDSessionCollection`
  - `xRDSessionCollectionConfiguration`
  - `xRDSessionDeployment`

But `xRDLicenseConfiguration` is missing. How can I access `xRDLicenseConfiguration`?

**Comment by danielboth** [comment]
Hi @mjcarrabine,

I just verified that xRDLicenseConfiguration is available in the latest release of xRemoteDesktopSessionHost, which is 1.8.0.0 at this moment. If you pull that version from the PSGallery you will be able to use the xRDLicenseConfiguration resource.

**Comment by danielboth** [comment]
I'm considering this answer solved, let me know if you have any more questions @mjcarrabine.
