### ISSUE TITLE
Collectionname max 15 charaters, why?

### ISSUE THREAD

**Issue by Sawal72** [PowerShell/xRemoteDesktopSessionHost#60]

**Comment by johlju** [comment]
See issue #10. Is this not an issue anymore? Or was this an issue on an older operating system?

**Comment by Sawal72** [comment]
I need to find time to check it. We have bypass this issue, we had create an own module based on the gallery module.

Mvg Sander Walraven

**Comment by johlju** [comment]
Would be great if you could help to see (or know) if there is a limit in any operating system 2012 R2 and newer, if not we could just remove that limit altogether.

**Comment by johlju** [comment]
See comment in PR #61  https://github.com/PowerShell/xRemoteDesktopSessionHost/pull/61#issuecomment-523625254 which can explain why this parameter has a limit of 15 characters.
