### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by gmatusko** [PowerShell/xRemoteDesktopSessionHost#8]
We've been working with the xRemoteDesktopSessionHost DSC module that is included with azure-quickstart-templates/rds-deployment/.  This module includes several other resources for configuring a RDS environment that are not included in this published version.  I assume these were built by the RDS team but it would be nice if they were either combined into this module or a new DSC module created (something like xRemoteDesktopConfiguration) to include the resources that are missing from this module.  Those resources are:

xRDGatewayConfiguration
xRDLicenseConfiguration
xRDServer

Let us know if there are any plans to provide/maintain these in the PowerShell Gallery.

Thanks...Greg

**Comment by freni59** [comment]
All mentioned above, both in Greg's and Jordan's is needed for this resource to be usefull in bigger automation scenarios, or even small for that matter...

**Comment by ld0614** [comment]
@kwirkykat Do you see any licensing / copyright implications from taking the latest version from the quickstart gallery and merging it back into this repository?  I've checked the module and it still ships with an MIT license and looks like it was a direct fork at some point in the past.

**Comment by johlju** [comment]
@mgreenegit @kwirkykat can you give a quick answer on @ld0614 question? We are about doing something similar in xFailOverCluster, moving code from a quick start template.

**Comment by johlju** [comment]
As per @scottpas issue #31 these are also located here  https://github.com/Azure/RDS-Templates/tree/master/DSC/Configuration/xRemoteDesktopSessionHost/DSCResources one option is to move what is missing there instead.

**Comment by mgreenegit** [comment]
Yes, let's merge work from the quickstart templates to the DSC resources.  Both use the MIT license so it is safe to do, and I will let their team know.  It would be nice to give credit in the readme.

**Comment by johlju** [comment]
Then we have a go, so If someone in the community like start adding these resource here, feel free.

**Comment by ld0614** [comment]
I've just made public the work that I've been doing to merge the quickstart DSC and upgrade the module to support High Availability.  This work can be found  [here](https://github.com/ld0614/xRemoteDesktopSessionHost/tree/QuickStartMerge).  

I believe the code to be working (its already in production with some clients) however there are a couple of linting failures and a complete lack of unit testing for the PR.  I hope to fix these issues over the next few weeks prior to submitting a formal PR.  

Obviously I'm more that happy to receive feedback on the changes, please let me know if anyone has any comments, suggestions or concerns.

@kwirkykat This work is split across the quickstart template work, work completed personally (I've already signed a personal CLA) and work completed on behalf of the company I work for (PowerON Platforms).  I've got documented approval to submit the corporate work into the Resource kit however as I've only signed a personal CLA, do I need to sign anything else prior to submitting a PR?

**Comment by ld0614** [comment]
@johlju when I went to the CLA bot I wasn't able to change my declaration from personal to on behalf of a business, while this may not be an issue I just wanted to be completely upfront with the provenance of the code to ensure that there are no issues in the future

**Comment by johlju** [comment]
@id0614 I see now what you mean about “behalf of a business”. In this link https://cla.opensource.microsoft.com there is a sample pdf that has the “behalf of a business”, but the CLA in the checks section in the PR’s does not? 🤔

**Comment by johlju** [comment]
@ld0614 I will try to sort this out next week so we get a clear answer.

**Comment by johlju** [comment]
@ld0614 I have a contact now, and I will send you an e-mail.

**Comment by johlju** [comment]
I think this was resolved in PR #33.
